###########################################
#             Configuration               #
#           Plugin by SparnetXD           #
###########################################

# General Settings
settings:
  enable_feature: true
  message_color: "&a"

# Default Settings for Live Players
live_player_defaults:
  message: "Players will now see in the TAB that you are LIVE!"

# Default Settings for Not Live Players
not_live_player_defaults:
  message: "Players will no longer see that you are live in the TAB!"

# Custom Message Settings
messages:
  live_on: "&aPlayers will now see in the TAB that you are LIVE!"
  live_off: "&cPlayers will no longer see that you are live in the TAB!"
